name: Build and Deploy the Solution

on:
  workflow_call:

jobs:
  core-infrastructure-rollout:
    runs-on: [self-hosted, linux]
    environment: han
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

  build:
    needs: core-infrastructure-rollout
    runs-on: [self-hosted, linux]
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet build --configuration Release
      
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/webapi
  
  deploy:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/webapi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'han-webapi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/webapi
