name: Build and Deploy the Solution

on:
  workflow_call:

jobs:
  core-infrastructure-rollout:
    runs-on: [self-hosted, linux]
    environment: han
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Build
        run: dotnet build --configuration Release
      
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapi