name: Build and Deploy the Solution

on:
  workflow_call:

jobs:
  solution-build-and-deploy:
    runs-on: [self-hosted, linux]
    environment: han
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Build the solution
        run: dotnet build WebApi --configuration Release
      
      - name: Publish the solution
        run: dotnet publish WebApi -c Release -o ${{env.DOTNET_ROOT}}/webapi
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-we-han'
          package: ${{env.DOTNET_ROOT}}/webapi