name: SQL Prep

on:
  workflow_call:
    inputs:
      connectionstring:
        description: 'The connection string to the SQL Server'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      connectionstring:
        description: 'The connection string to the SQL Server'
        required: true
        type: string

jobs:
  core-infrastructure-rollout:
    runs-on: [ubuntu-latest]
    environment: han
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          enable-AzPSSession: true
    
      - uses: azure/sql-action@v2.1
        with:
          connection-string: ${{ inputs.connectionstring }}
          path: sql/initialconfig.sql
